### PR TITLE
Add error for undeflow condition

### PR DESCRIPTION
**Pull request by Kubuxu**

### CODE REVIEW

**Review by ribasushi — APPROVED** [review]
LGTM

**Review by raulk — COMMENTED** [review]
Hum, while this would’ve been the right thing to do from the outset, there may be library users now that rely on the zero case not returning an error. Would like @stebalien to pitch in. While this is not an interface change, such a behaviour change in a deep component like this could wreak havoc.

**Comment by raulk** [comment]
Can you live with the current behaviour? Or you really need to disambiguate against other possible scenarios where a 0, 0 could be returned without an error? (If yes, can you give some examples?)

**Comment by Kubuxu** [comment]
I would prefer to not have to live with current behavior because it is bug inducing. I've already worked around it in lotus.

The truth is that `n=0` gives invalid output and should be an error.

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
This is definitely an error and nobody should be relying on this behavior (this is new and newly buggy code).

@Kubuxu could you make sure to audit the rest of this code? I don't think it has ever been reviewed.

**Pull request merged**
